const fs = require("fs");
const path = require("path");
const root = __dirname;
const input = path.resolve(root, process.argv[2] || "newsletter-data.json");
let data = JSON.parse(fs.readFileSync(input, "utf8"));
if (data.source) data = JSON.parse(fs.readFileSync(path.resolve(path.dirname(input), data.source), "utf8"));
const template = fs.readFileSync(path.join(root, "newsletter-template.html"), "utf8");
const esc = (v = "") => String(v).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const url = (v = "") => /^(https?:|mailto:|tel:|sms:)/i.test(String(v).trim()) ? esc(String(v).trim()) : "";
const paras = (values = []) => values.map(v => `<p style="margin:12px 0 0;">${esc(v)}</p>`).join("");
const featureSection = (feature, color, background) => `<tr><td style="padding:10px 28px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:${background};border-left:5px solid ${color};"><tr><td style="padding:22px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:24px;color:#243447;"><div style="font-size:12px;font-weight:bold;letter-spacing:1px;color:${color};">${esc(feature.type).toUpperCase()}</div><div style="padding-top:7px;font-size:20px;line-height:27px;font-weight:bold;color:#16324f;">${esc(feature.title)}</div>${feature.location ? `<div style="padding-top:4px;font-size:13px;color:#56697a;">${esc(feature.location)}</div>` : ""}${paras(feature.paragraphs)}${feature.items?.length ? `<ul style="margin:12px 0 0;padding-left:22px;">${feature.items.map(x => `<li style="margin:5px 0;">${esc(x)}</li>`).join("")}</ul>` : ""}${feature.sourceUrl ? `<p style="margin:14px 0 0;font-size:12px;"><a href="${url(feature.sourceUrl)}" style="color:${color};text-decoration:underline;">Source</a></p>` : ""}</td></tr></table></td></tr>`;
const note = `<div style="font-size:12px;font-weight:bold;letter-spacing:1px;color:#a65a00;">DANNY'S NOTE</div>${paras(data.dannysNote.split(/\r?\n\r?\n/))}`;
const marketRows = data.marketSnapshot.counties.map(c => `<tr><td style="padding:9px;border-top:1px solid #cbdbea;"><strong>${esc(c.name)}</strong><br><span style="font-size:13px;">Median list price: ${esc(c.medianListingPrice)} &nbsp;•&nbsp; Active listings: ${esc(c.activeListings)} &nbsp;•&nbsp; Median days on market: ${esc(c.medianDaysOnMarket)}</span></td></tr>`).join("");
const market = `<div style="font-size:12px;font-weight:bold;letter-spacing:1px;color:#2563eb;">GWINNETT &amp; BEYOND MARKET SNAPSHOT</div><div style="padding-top:7px;font-size:20px;line-height:27px;font-weight:bold;color:#16324f;">${esc(data.marketSnapshot.title)}</div><p style="margin:10px 0;">${esc(data.marketSnapshot.intro)}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">${marketRows}</table><p style="margin:12px 0 0;font-size:12px;">Source: <a href="${url(data.marketSnapshot.sourceUrl)}" style="color:#2563eb;">${esc(data.marketSnapshot.sourceLabel)}</a>; ${esc(data.marketSnapshot.period)}.</p>`;
const cartoonVisual = data.cartoon.imageUrl ? `<img src="${url(data.cartoon.imageUrl)}" width="500" alt="${esc(data.cartoon.imageAlt)}" style="display:block;width:100%;max-width:500px;height:auto;margin:14px auto 0;border:0;">` : `<div style="margin-top:14px;padding:20px;background:#fffdf3;border:1px solid #ead17a;text-align:center;font-style:italic;color:#5f4b00;">${esc(data.cartoon.fallbackText)}</div>`;
const values = { SUBJECT_LINE: esc(data.subjectLine), PREVIEW_TEXT: esc(data.previewText), ISSUE_DATE: esc(data.issueDate), DANNYS_NOTE: note, MARKET_SNAPSHOT: market, FEATURE_ONE: featureSection(data.features[0], "#b45309", "#fff7ed"), FEATURE_TWO: featureSection(data.features[1], "#15803d", "#f0fdf4"), CARTOON: `${cartoonVisual}<div style="padding-top:14px;text-align:center;font-size:19px;line-height:27px;font-weight:bold;color:#5f4b00;">${esc(data.cartoon.caption)}</div>` };
let html = template;
for (const [key, value] of Object.entries(values)) html = html.replaceAll(`{{${key}}}`, value);
const unresolved = html.match(/{{[^}]+}}/g);
if (unresolved) throw new Error(`Unresolved template fields: ${unresolved.join(", ")}`);
const dist = path.join(root, "dist"); fs.mkdirSync(dist, { recursive: true });
const base = path.join(dist, `gwinnett-and-beyond-${data.issueDateIso}.html`);
let archive = base;
if (fs.existsSync(base) && fs.readFileSync(base, "utf8") !== html) { let v = 2; while (fs.existsSync(path.join(dist, `gwinnett-and-beyond-${data.issueDateIso}-v${v}.html`))) v++; archive = path.join(dist, `gwinnett-and-beyond-${data.issueDateIso}-v${v}.html`); }
if (!fs.existsSync(archive)) fs.writeFileSync(archive, html, "utf8");
fs.writeFileSync(path.join(dist, "newsletter.html"), html, "utf8");
fs.writeFileSync(path.join(root, "index.html"), html, "utf8");
console.log(JSON.stringify({ issueDate: data.issueDateIso, archive, latest: path.join(dist, "newsletter.html") }, null, 2));
